options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Docker Build
  - id: Build
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Step 1: Building Docker image..."
        docker build -t us-central1-docker.pkg.dev/solar-imprint-427818-r2/k8s/k8s-container2 .
        echo "Docker image built successfully."

  # Docker Push
  - id: Push
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Step 2: Pushing Docker image..."
        docker push --all-tags us-central1-docker.pkg.dev/solar-imprint-427818-r2/k8s/k8s-container2
        echo "Image pushed successfully."

  - id: Update GKE
    name: "gcr.io/cloud-builders/kubectl"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Step 4: Updating pod by setting new image...."
        gcloud container clusters get-credentials k8s-assignment --zone us-central1-c --project ${PROJECT_ID}
        echo "${PROJECT_ID}"
        kubectl get deployment con2-deployment || kubectl apply -f manifest.yaml
        kubectl set image deployment/con2-deployment k8s-container2=us-central1-docker.pkg.dev/solar-imprint-427818-r2/k8s/k8s-container2
        echo "Image updated successfully."
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=k8s-assignment'

