substitutions:
  _IMAGE_NAME: "us-central1-docker.pkg.dev/solar-imprint-427818-r2/k8s/k8s-container2"
  _DEPLOYMENT_NAME: "container2"
  _DEPLOYMENT_LABEL: "k8s-container2"
  _CLUSTER_NAME: "k8s-assignment"


options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Docker Build
  - id: Build
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Building Docker image..."
        docker build -t $_IMAGE_NAME:${SHORT_SHA} .
        echo "Docker image built successfully."

  # Docker Push
  - id: Push
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Pushing Docker image..."
        docker push $_IMAGE_NAME:${SHORT_SHA}
        echo "Image pushed successfully."

  - id: Update GKE
    name: "gcr.io/cloud-builders/kubectl"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Updating Deployment"
        gcloud container clusters get-credentials k8s-assignment --zone us-central1-c --project ${PROJECT_ID}
        kubectl get deployment $_DEPLOYMENT_NAME || kubectl apply -f manifest.yaml
        kubectl set image deployment/$_DEPLOYMENT_NAME $_DEPLOYMENT_LABEL=$_IMAGE_NAME:${SHORT_SHA}
        echo "Deployment updated successfully."
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'
